<option value="Project Manager">Project Manager</option>
<option value="Ing Mecánico">Ing Mecánico</option>
<option value="Ing Eléctrico">Ing Eléctrico</option>
<option value="Ing. De procesos">Ing. De procesos</option>
<option value="Ing. Calculista">Ing. Calculista</option>
<option value="I&C">I&C</option>
<option value="Jefe de Obra">Jefe de Obra</option>
<option value="Encargado de Obra">Encargado de Obra</option>
<option value="Recurso Preventivo">Recurso Preventivo</option>
<option value="Calculista de fachadas">Calculista de fachadas</option>
<option value="Trazadista">Trazadista</option>
<option value="Delineante instalaciones mecánicas">Delineante instalaciones mecánicas</option>
<option value="Delineante instalaciones eléctricas">Delineante instalaciones eléctricas</option>
<option value="Delineante estructuras metálicas">Delineante estructuras metálicas</option>
<option value="Diseñador Industrial">Diseñador Industrial</option>
<option value="Diseñador de tuberías">Diseñador de tuberías</option>
<option value="Proyectista muro cortina">Proyectista muro cortina</option>
<option value="Modelador BIM">Modelador BIM</option>
<option value="Programador PLC">Programador PLC</option>
<option value="PRL">PRL</option>
<option value="Administrativo de Obra">Administrativo de Obra</option>