<optgroup label="Mecánica">
    <option value="SOLIDWORKS">SOLIDWORKS</option>
    <option value="SOLIDEDGE">SOLIDEDGE</option>
    <option value="CATIA">CATIA</option>
    <option value="INVENTOR">INVENTOR</option>
    <option value="CREO (PRO ENGINEER)">CREO (PRO ENGINEER)</option>
    <option value="AUTOCAD 2D">AUTOCAD 2D</option>
    <option value="AUTOCAD CÁLCULO">AUTOCAD CÁLCULO</option>
    <option value="AUTOCAD MECHANICAL">AUTOCAD MECHANICAL</option>
    <option value="ANSYS">ANSYS</option>
    <option value="TOP SOLID">TOP SOLID</option>
</optgroup>
<optgroup label="Arquitectura">
    <option value="REVIT">REVIT</option>
    <option value="REVIT ARQ">REVIT ARQ</option>
    <option value="REVIT MEP">REVIT MEP</option>
    <option value="REVIT STRUC">REVIT STRUC</option>
    <option value="AECOSIM">AECOSIM</option>
    <option value="AUTOCAD 2D / 3D">AUTOCAD 2D / 3D</option>
    <option value="SKETCH UP">SKETCH UP</option>
    <option value="NAVISWORKS">NAVISWORKS</option>
</optgroup>
<optgroup label="Obra Civil">
    <option value="TEKLA">TEKLA</option>
    <option value="ARMACAD">ARMACAD</option>
    <option value="AUTOCAD CIVIL 3D">AUTOCAD CIVIL 3D</option>
    <option value="CYPE">CYPE</option>
    <option value="SAP2000">SAP2000</option>
    <option value="STAAD PRO">STAAD PRO</option>
    <option value="TRICALC">TRICALC</option>
    <option value="PRESTO">PRESTO</option>
    <option value="MENFIS">MENFIS</option>
    <option value="ARQUÍMEDES">ARQUÍMEDES</option>
    <option value="ArchiCAD">ArchiCAD</option>
    <option value="MICROSTATION">MICROSTATION</option>
    <option value="ISPOL">ISPOL</option>
</optgroup>
<optgroup label="Industrial">
    <option value="AUTOCAD PLANT 3D">AUTOCAD PLANT 3D</option>
    <option value="SMART PLANT 3D">SMART PLANT 3D</option>
    <option value="SMART PLANT P&ID">SMART PLANT P&ID</option>
    <option value="PDMS">PDMS</option>
    <option value="PDS">PDS</option>
    <option value="PDS FRAMEWORKS">PDS FRAMEWORKS</option>
    <option value="NAVISWORKS">NAVISWORKS</option>
    <option value="ASPEN HYSYS">ASPEN HYSYS</option>
    <option value="HTRI">HTRI</option>
    <option value="AVEVA Diagrams">AVEVA Diagrams</option>
    <option value="InPlant">InPlant</option>
    <option value="PipePhase">PipePhase</option>
    <option value="PipeFLO">PipeFLO</option>
    <option value="Draftsight">Draftsight</option>
</optgroup>